services:
  postgresql:
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-tmdl_db}

  redis:
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-123}
